export const iconMap: { [key: string]: any } = {
  '1': require('../assets/aircraft/1.png'),
  '1red': require('../assets/aircraft/1red.png'),
  '2': require('../assets/aircraft/2.png'),
  '2red': require('../assets/aircraft/2red.png'),
  '3': require('../assets/aircraft/3.png'),
  '3red': require('../assets/aircraft/3red.png'),
  '4': require('../assets/aircraft/4.png'),
  '4red': require('../assets/aircraft/4red.png'),
  '5': require('../assets/aircraft/5.png'),
  '5red': require('../assets/aircraft/5red.png'),
  '6': require('../assets/aircraft/6.png'),
  '6red': require('../assets/aircraft/6red.png'),
  '7': require('../assets/aircraft/7.png'),
  '7red': require('../assets/aircraft/7red.png'),
};
